<?php
/** @var $block Siscom\RecuperaCarrinho\Block\Adminhtml\System\Config\Form\Button */
?>
<?= $block->getChildHtml('button') ?>
<span class="reminder-indicator" id="reminder_button">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px"
         src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="remindered" hidden="hidden" alt="Collected" style="margin:-3px 5px"
         src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="reminder_message_span"></span>
</span>

<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {

        jQuery('#reminder_button').click(function () {
            generatebutton();
        });

        function generatebutton() {
            var reminderSpan = jQuery('#reminder_button');
            new Ajax.Request('<?= $block->getAjaxCheckUrl() ?>', {
                method: 'get',
                loaderArea: true,
                asynchronous: true,
                onCreate: function () {
                    reminderSpan.find('.remindered').hide();
                    reminderSpan.find('.processing').show();
                    jQuery('#reminder_message_span').text('');
                },
                onSuccess: function (response) {
                    reminderSpan.find('.processing').hide();

                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        resultText = 'Success';
                        reminderSpan.find('.remindered').show();
                    }
                    jQuery('#reminder_message_span').text(resultText);

                    var json = response.responseJSON;
                    if (typeof json.time != 'undefined') {
                        jQuery('#row_mageworx_alsobought_general_inventory_time').find('.value .time').text(json.time);
                    }
                }
            });
        }

    });
</script>
